# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UMED
email: contato@umed.com
description: É a maneira mais facil de manter seus exames em dia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://umed.com.br" # the base hostname & protocol for your site
twitter_username: biacp87
github_username:  beatrizcp87

# Build settings
markdown: kramdown
